
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: sinadumi
  password:
  timeout: 5000

development:
  <<: *default
  database: db/sinadumi_development

test:
  <<: *default
  database: db/sinadumi_test

production:
  <<: *default
  adapter: postgresql
  database: db/sinadumi_production.postgresql

  # postgresql start -> pg_ctl start -D /usr/local/Cellar/postgres
  # table -> psql -l
  # rails dbconsole 

